language: julia

os:
  - osx
  - linux

julia:
  - 0.5
  - release

notifications:
  email: false

before_install:
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/DivSigGrad.jl","DivSigGrad"); Pkg.build("DivSigGrad");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/Multigrid.jl","Multigrid"); Pkg.build("Multigrid");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/FactoredEikonalFastMarching.jl.git","FactoredEikonalFastMarching"); Pkg.build("FactoredEikonalFastMarching");'
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ForwardHelmholtz"); Pkg.test("ForwardHelmholtz"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ForwardHelmholtz")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
