language: julia

os:
  - osx
  - linux

julia:
  - 0.4
  - release
  
notifications:
  email: false
 
before_install:
   - julia -e 'Pkg.clone("https://github.com/lruthotto/KrylovMethods.jl","KrylovMethods"); Pkg.build("KrylovMethods");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl","jInv"); Pkg.build("jInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/EikonalInv.jl","EikonalInv"); Pkg.build("EikonalInv");'
   - julia -e 'Pkg.clone("https://github.com/JuliaInv/Multigrid.jl","Multigrid"); Pkg.build("Multigrid");'
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("ForwardHelmholtz"); Pkg.test("ForwardHelmholtz"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ForwardHelmholtz")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
